---

- name: Add Jenkins stable APT key
  apt_key: url='https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key'

- name: Add Jenkins stable APT repository
  apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/'

- name: Install Java # needs to be configured before Jenkins
  apt: name=openjdk-11-jdk state=present

- name: Install packages
  apt:
    state: present
    name:
      - jenkins
      - xmlstarlet
      - python-httplib2
      - git

- name: Add Jenkins user to shadow group
  user: name=jenkins groups=shadow append=yes

- name: Create Jenkins job storage directory (parent)
  file: path=/srv/jenkins-data state=directory owner=root group=root mode=0755

- name: Create Jenkins job storage directory
  file: path=/srv/jenkins-data/jobs state=directory owner=jenkins group=jenkins mode=0755

- name: Link Jenkins job storage directory
  file: src=/srv/jenkins-data/jobs path=/var/lib/jenkins/jobs state=link

- name: Set permissions for AFP devel site
  file: path=/var/www/afp-devel state=directory owner=jenkins group=root mode=0755

- name: Check initial setup
  shell: test -f /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_initial
  failed_when: False

- name: Check Jenkins service status
  shell: service jenkins status
  args:
    warn: False
  register: jenkins_status
  failed_when: False

- name: Start Jenkins
  service: name=jenkins state=started
