---

- name: Add Jenkins stable APT key
  apt_key: url='http://pkg.jenkins-ci.org/debian-stable/jenkins.io.key'

- name: Add Jenkins stable APT repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian-stable binary/'

- name: Install Java # needs to be configured before Jenkins
  apt: name=openjdk-8-jre state=present

- name: Install packages
  apt:
    state: present
    name:
      - jenkins
      - xmlstarlet
      - python-httplib2

- name: Add Jenkins user to shadow group
  user: name=jenkins groups=shadow append=yes

- name: Set permissions for AFP devel site
  file: path=/var/www/afp-devel state=directory owner=jenkins group=root mode=0755

- name: Jenkins basic configuration
  lineinfile: dest=/etc/default/jenkins regexp=^JENKINS_ARGS line='JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort={{ config.jenkins.port }} --ajp13Port=-1 --prefix=$PREFIX"'
  register: jenkins_conf

- name: Check initial setup
  shell: test -f /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_initial
  failed_when: False

- name: Warn for automatic stopping
  pause:
    prompt: "Jenkins will be automatically stopped; continuing in 10 seconds"
    seconds: 10
  when: "jenkins_initial.rc == 0 and jenkins_conf.changed"

- name: Stop Jenkins in initial setup (if necessary)
  service: name=jenkins state=stopped
  when: "jenkins_initial.rc == 0 and jenkins_conf.changed"

- name: Check Jenkins service status
  shell: service jenkins status
  args:
    warn: False
  register: jenkins_status
  failed_when: False

- name: Stop Jenkins manually in non-initial setup (if necessary)
  fail: msg="Jenkins needs to be stopped manually"
  when: "jenkins_conf.changed and jenkins_status.rc == 0"

- name: Start Jenkins
  service: name=jenkins state=started
