---

- name: Prepare Jenkins job definitions
  file: path=/home/admin/jobs state=directory owner=root group=root mode=0644

- name: Copy Jenkins job definitions
  template: src=jobs/{{ item }}.xml dest=/home/admin/jobs/{{ item }}.xml owner=root group=root mode=0644
  loop: "{{ config.jenkins.jobs }}"

- name: List Jenkins jobs
  shell: /home/admin/cli.sh list-jobs
  register: jenkins_jobs
  failed_when: "jenkins_jobs.stderr != ''"

- name: Create missing Jenkins jobs
  shell: /home/admin/cli.sh create-job {{ item }} < /home/admin/jobs/{{ item }}.xml
  when: "item not in jenkins_jobs.stdout_lines"
  loop: "{{ config.jenkins.jobs }}"

- name: Update existing Jenkins jobs
  shell: /home/admin/cli.sh update-job {{ item }} < /home/admin/jobs/{{ item }}.xml
  when: "item in jenkins_jobs.stdout_lines"
  loop: "{{ config.jenkins.jobs }}"
