---

- name: Create administrative user
  user: name=admin uid=901 shell=/bin/false password={{ config.jenkins.password | password_hash('sha512') }}

- name: Copy Jenkins CLI script
  template: src=cli.sh dest=/home/admin/cli.sh owner=root group=root mode=0700

- name: Copy private SSH key for workers
  copy: content="{{ config.jenkins.ssh_key }}" dest=/home/admin/jenkins-worker owner=jenkins group=jenkins mode=0600

- name: Create node cronjobs
  template: "src=node-up.sh dest=/etc/cron.hourly/node-up-{{ hostvars[item]['worker_name'] }} owner=root group=root mode=0755"
  loop: "{{ groups['worker'] }}"
  tags:
    - jenkins-workers

- name: Wait for Jenkins to respond properly
  uri: url=https://{{ config.domains.jenkins }}/jenkins/whoAmI/ return_content=yes validate_certs=no
  register: jenkins_startup
  until: jenkins_startup is success
  retries: 10
  delay: 10

- name: Install Jenkins CLI
  get_url: url=http://{{ config.domains.jenkins }}/jenkins/jnlpJars/jenkins-cli.jar dest=/home/admin/jenkins-cli.jar mode=0644 validate_certs=no
