---

- name: Copy Groovy script
  template: src={{ item }} dest=/home/admin/{{ item }} owner=root group=root mode=0600
  loop: "{{ config.jenkins.scripts }}"

- name: Run Groovy script
  shell: "/home/admin/cli.sh groovy = < /home/admin/{{ item }}"
  loop: "{{ config.jenkins.scripts }}"

- name: Set permission for security kill switch
  file: path=/var/lib/jenkins/secrets/slave-to-master-security-kill-switch owner=root group=root mode=0644
