---

- name: Connect SSH nodes
  shell: "/home/admin/cli.sh connect-node {{ hostvars[item]['worker_name'] }} 2>/dev/null"
  loop: "{{ groups['worker'] }}"
  ignore_errors: True
  tags:
    - jenkins-workers

- name: Check security kill switch
  command: /home/admin/cli.sh groovy =
  args:
    stdin: "assert(!jenkins.model.Jenkins.getInstance().getExtensionList(jenkins.security.s2m.AdminWhitelistRule.class).get(jenkins.security.s2m.AdminWhitelistRule.class).getMasterKillSwitch())"
