---

- name: Allow port 443
  shell: firewall-cmd --zone=public --add-port=443/tcp --permanent

- name: Make lxcbr0 trusted
  shell: firewall-cmd --zone=trusted --change-interface=lxcbr0 --permanent

- name: Open trusted subnet
  shell: firewall-cmd --zone=trusted --add-source=131.159.0.0/16 --permanent

- name: Reload rules
  shell: firewall-cmd --reload