---

- name: Install packages
  apt:
    state: present
    update_cache: yes
    name:
      - openjdk-17-jre
      - mercurial
      - slurmctld
      - nfs-kernel-server

- name: Prepare Jenkins home directory
  file: path=/media/data state=directory owner=root group=root mode=0755

- name: Create Jenkins user
  user: name=jenkins uid=902 shell=/bin/sh home={{ config.worker.jenkins_home }}

- name: Prepare .ssh directory
  file: path={{ config.worker.jenkins_home }}/.ssh state=directory owner=jenkins group=root mode=0700

- name: Copy authorized_keys file
  copy: src=authorized_keys dest={{ config.worker.jenkins_home }}/.ssh/authorized_keys owner=jenkins group=root mode=0644

- name: Link Java
  file: src=/usr/bin/java path={{ config.worker.jenkins_home }}/java state=link

- name: Create slurmctld spool dir
  file: path=/var/spool/slurmctld state=directory owner=slurm group=slurm mode=0751

- name: Create slurmctld log dir
  file: path=/var/log/slurmctld state=directory owner=slurm group=slurm mode=0751

- name: Enable slurm controller daemon
  service: name=slurmctld enabled=true state=restarted

- name: Prepare Isabelle user home dir
  file: path={{ config.worker.jenkins_home }}/.isabelle state=directory owner=jenkins group=root mode=0755

- name: Prepare Isabelle home dir
  file: path={{ config.worker.jenkins_home }}/workspace/isabelle-distributed state=directory owner=jenkins group=jenkins mode=0775

- name: Prepare Isabelle heaps dir
  file: path={{ config.worker.jenkins_home }}/workspace/heaps state=directory owner=slurm group=slurm mode=0777

- name: Prepare Isabelle browser info dir
  file: path={{ config.worker.jenkins_home }}/workspace/browser_info state=directory owner=slurm group=slurm mode=0777

- name: Enable NFS sharing (read-only Isabelle home+user home, write-access heaps)
  blockinfile:
    name: /etc/exports
    block: |
      {{ config.worker.jenkins_home }}/workspace/isabelle-distributed localhost(ro,sync,no_subtree_check) {{ groups['slurm_worker'] | product(['(ro,sync,no_subtree_check)']) | map('join') | join(' ') }}
      {{ config.worker.jenkins_home }}/.isabelle localhost(ro,sync,no_subtree_check) {{ groups['slurm_worker'] | product(['(ro,sync,no_subtree_check)']) | map('join') | join(' ') }}
      {{ config.worker.jenkins_home }}/workspace/heaps localhost(ro,sync,no_subtree_check) {{ groups['slurm_worker'] | product(['(ro,sync,no_subtree_check)']) | map('join') | join(' ') }}
      {{ config.worker.jenkins_home }}/workspace/browser_info localhost(ro,sync,no_subtree_check) {{ groups['slurm_worker'] | product(['(ro,sync,no_subtree_check)']) | map('join') | join(' ') }}

- name: Start and enable NFS service
  service: name=nfs-kernel-server enabled=true state=restarted

- name: Reload exports
  shell: exportfs -ra