---

- name: Prepare Isabelle
  file: path={{ config.worker.jenkins_home }}/.isabelle/etc state=directory owner=jenkins group=root mode=0755

- name: Copy Isabelle settings
  template: src=settings dest={{ config.worker.jenkins_home }}/.isabelle/etc/settings owner=jenkins group=root mode=0644 follow=yes
