---

- name: Install packages
  apt:
    state: present
    update_cache: yes
    name:
      - python3-pip
      - mariadb-server

- name: Add slurm config
  copy: src=40-mysqld-slurm.cnf dest=/etc/mysql/mariadb.conf.d/40-mysqld-slurm.cnf

- name: Start mariadb
  service: name=mariadb enabled=true state=restarted

- name: Set mysql root password
  become: true
  shell: "mysqladmin -u root password '{{ config.slurm.db_password }}'"

- name: Enable pymsql for ansible
  become: true
  pip:
    name: pymysql
    state: present

- name: Create mysql user
  become: true
  mysql_user:
    login_password: "{{ config.slurm.db_password }}"
    login_user: root
    name: slurm
    password: "{{ config.slurm.db_password }}"
    priv: '*.*:ALL'
    state: present

- name: Create mysql db
  become: true
  mysql_db:
    login_password: "{{ config.slurm.db_password }}"
    login_user: root
    name: slurm_acct_db
    state: present
