---

- name: Install packages
  apt:
    state: present
    update_cache: yes
    name:
      - nfs-kernel-server

- name: Prepare Isabelle user home dir
  file: path={{ config.worker.jenkins_home }}/.isabelle state=directory owner=jenkins group=root mode=0755

- name: Prepare Isabelle home dir
  file: path={{ config.worker.jenkins_home }}/workspace/isabelle-distributed state=directory owner=jenkins group=jenkins mode=0775

- name: Prepare Isabelle heaps dir
  file: path={{ config.worker.jenkins_home }}/workspace/heaps state=directory owner=slurm group=slurm mode=0777

- name: Prepare Isabelle browser info dir
  file: path={{ config.worker.jenkins_home }}/workspace/browser_info state=directory owner=slurm group=slurm mode=0777

- name: Enable NFS sharing (read-only Isabelle home+user home, write-access heaps)
  blockinfile:
    name: /etc/exports
    block: |
      {{ config.worker.jenkins_home }}/workspace/isabelle-distributed localhost(ro,sync,no_subtree_check) {{ groups['slurm_worker'] | product(['(ro,sync,no_subtree_check)']) | map('join') | join(' ') }}
      {{ config.worker.jenkins_home }}/.isabelle localhost(ro,sync,no_subtree_check) {{ groups['slurm_worker'] | product(['(ro,sync,no_subtree_check)']) | map('join') | join(' ') }}
      {{ config.worker.jenkins_home }}/workspace/heaps localhost(rw,sync,no_subtree_check) {{ groups['slurm_worker'] | product(['(rw,sync,no_subtree_check)']) | map('join') | join(' ') }}
      {{ config.worker.jenkins_home }}/workspace/browser_info localhost(rw,sync,no_subtree_check) {{ groups['slurm_worker'] | product(['(rw,sync,no_subtree_check)']) | map('join') | join(' ') }}

- name: Start and enable NFS service
  service: name=nfs-kernel-server enabled=true state=restarted

- name: Reload exports
  shell: exportfs -ra