---

- name: Install packages
  apt:
    state: present
    update_cache: yes
    name:
      - openjdk-17-jre
      - curl
      - m4
      - libgomp1
      - libgmp-dev
      - unzip
      - swi-prolog
      - smlnj
      - lib32stdc++6
      - texlive-full
      - libzarith-ocaml
      - cpufrequtils

- name: Set performance governor
  lineinfile: name=/etc/default/cpufrequtils line="GOVERNOR=performance" create=true owner=root group=root

- name: Enable cpu freq utils
  service: name=cpufrequtils.service enabled=yes daemon_reload=yes state=restarted

- name: Create cluster user
  user: name=cluster shell=/bin/bash group=isabelle home=/home/cluster

- name: Prepare cluster .ssh directory
  file: path=/home/cluster/.ssh state=directory owner=cluster group=root mode=0700

- name: Copy cluster authorized_keys file
  copy: src=authorized_keys dest=/home/cluster/.ssh/authorized_keys owner=cluster group=root mode=0600

- name: Create build user
  user: name=build shell=/bin/bash home={{ config.build.home }} group=isabelle system=yes

- name: Prepare build .ssh directory
  file: path={{ config.build.home }}/.ssh state=directory owner=build group=root mode=0700

- name: Copy build authorized_keys file
  copy: src=authorized_keys dest={{ config.build.home }}/.ssh/authorized_keys owner=build group=root mode=0600