---

- name: Prepare Isabelle home
  file: path=/home/cluster/.isabelle/build_cluster/etc state=directory owner=cluster group=cluster

- name: Copy Isabelle cluster preferences
  template: src=preferences dest=/home/cluster/.isabelle/build_cluster/etc/preferences owner=cluster group=cluster mode=0700