---

- name: Enable Apache modules
  apache2_module: name={{ item }}
  with_items:
    - cgid
    - proxy
    - proxy_http
    - ssl
    - rewrite
    - include
    - headers

- name: Disable default Apache site
  shell: a2dissite 000-default.conf

- name: Prepare Apache web roots
  file: path={{ item }} state=directory
  with_items: "{{ config.apache.webroots }}"

- name: Obtain AFP submission host
  set_fact: afp_submission_host={{ groups['afp'][0] }}

- name: Configure Apache
  template: src={{ item }} dest=/etc/apache2/sites-enabled/{{ item }} owner=root group=root mode=0644
  with_items: "{{ config.apache.configs }}"

- name: Restart Apache
  service: name=apache2 state=restarted
