---

- name: Enable Apache modules
  apache2_module: name={{ item }}
  with_items:
    - cgid
    - proxy
    - proxy_http
    - headers

- name: Disable default Apache site
  shell: a2dissite 000-default.conf

- name: Prepare Apache configuration
  file: path=/var/www/afp state=directory owner=root group=root mode=0755

- name: Prepare assets
  file: path=/var/www/afp/{{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - img
    - lib

- name: Copy assets
  copy: src={{ item.src }} dest=/var/www/afp/{{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: 'jquery-3.1.1.min.js', dest: 'lib/jquery-3.1.1.min.js' }
    - { src: 'loader.gif', dest: 'img/loader.gif' }

- name: Create browser_info directory on data partition
  file: path=/media/data/browser_info state=directory owner=conrad group=root mode=0755

- name: Link browser_info directory
  file: path=/var/www/afp/browser_info src=/media/data/browser_info state=link

- name: Configure Apache
  copy: src=afp.conf dest=/etc/apache2/sites-enabled/afp.conf owner=root group=root mode=0644

- name: Restart Apache
  service: name=apache2 state=restarted
