---

- name: Clone application repository
  git: dest=/opt/afpbuild repo={{ config.afp.git }} force=yes

- name: Move config to application repository
  template: src=config.py dest=/opt/afpbuild/src/config.py owner=root group=root mode=0644

- name: Prepare application storage
  file: path=/var/afpbuild state=directory owner=root group=root mode=0755

- name: Prepare application storage (upload)
  file: path=/var/afpbuild/up state=directory owner=www-data group=root mode=0755

- name: Prepare application storage (download)
  file: path=/var/afpbuild/down state=directory owner=conrad group=root mode=0755

- name: Copy AFP submission service backend file
  copy: src=afp-submission-backend.service dest=/etc/systemd/system/afp-submission-backend.service owner=root group=root mode=0644

- name: Reload and restart afp-submission-backend.service
  service: name=afp-submission-backend.service enabled=yes daemon_reload=yes state=restarted

- name: Copy AFP submission service frontend file
  template: src=afp-submission-frontend.service dest=/etc/systemd/system/afp-submission-frontend.service owner=root group=root mode=0644

- name: Reload and restart afp-submission-frontend.service
  service: name=afp-submission-frontend.service enabled=yes daemon_reload=yes state=restarted