---

- name: Set default ACCEPT policy
  shell: iptables -P INPUT ACCEPT

- name: Flush firewall
  shell: iptables -F

- name: Prepare firewall
  file: path=/etc/iptables state=directory owner=root group=root mode=0755

- name: Copy firewall rules
  copy: src=rules.v4 dest=/etc/iptables/rules.v4 owner=root group=root mode=0644

- name: Load firewall rules
  shell: iptables-restore < /etc/iptables/rules.v4

- name: Make lxcbr0 trusted
  shell: firewall-cmd --zone=trusted --change-interface=lxcbr0 --permanent

- name: Open trusted subnet
  shell: firewall-cmd --zone=trusted --add-source=131.159.0.0/16 --permanent

- name: Reload rules
  shell: firewall-cmd --reload