---

- name: Prepare LXC configuration directory
  file: path={{ config.afp.container_home }}/.config/lxc state=directory owner=root group=root mode=0755

- name: Copy LXC configuration
  template: src=default.conf dest={{ config.afp.container_home }}/.config/lxc/default.conf owner=root group=root mode=0644

- name: Edit /etc/lxc/lxc-usernet
  lineinfile: name=/etc/lxc/lxc-usernet line='conrad veth lxcbr0 2'

- name: Restart lxc-net.service
  service: name=lxc-net.service state=restarted

- name: List LXC containers
  shell: lxc-ls -1
  register: afp_lxc
  become: yes
  become_user: conrad
  become_method: sudo

- name: Create LXC base container
  shell: lxc-create -n base -t download --bdev dir -- -d ubuntu -r focal -a amd64 --no-validate
  when: "afp_lxc.stdout.find('base') == -1"
  become: yes
  become_user: conrad
  become_method: sudo

- name: Copy resolv.conf
  copy: src=/etc/resolv.conf dest={{ config.afp.container_home }}/.local/share/lxc/base/rootfs/etc/resolv.conf remote_src=true owner=root group=root mode=0644

- name: Download Isabelle
  get_url: url=https://isabelle.in.tum.de/website-Isabelle2022/dist/Isabelle2022_linux.tar.gz dest=/media/data/isabelle2022.tar.gz checksum=sha256:e7fa6e9d9675d7a56751c00fa81ad0d081e1b6ffbdb0d7f02056853ba77f04c6

- name: Unpack Isabelle into LXC base container
  unarchive: src=/media/data/isabelle2022.tar.gz copy=false creates=Isabelle2022 dest={{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt owner=root group=root

- name: Clone AFP
  hg: dest={{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/afp repo=https://foss.heptapod.net/isa-afp/afp-2022 revision=default force=yes purge=yes

- name: Create .isabelle/Isabelle2022/etc/ in home dir of unprivileged user in container
  file:
    path: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/home/ubuntu/.isabelle/Isabelle2022/etc"
    owner: "10001001"
    group: "10001001"
    state: directory
    mode: 0755

- name: Configure Isabelle
  blockinfile:
    name: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/home/ubuntu/.isabelle/Isabelle2022/etc/settings"
    create: yes
    block: |
      ML_OPTIONS="-H 4000 --maxheap 6G"
      ML_HOME="$POLYML_HOME/$ML_PLATFORM"

- name: Build Isabelle sessions
  command: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/Isabelle2022/bin/isabelle build -o threads=2 -bv {{ item }}"
  with_items:
    - Pure
    - HOL
    - HOL-Library
    - HOL-Analysis
    - HOL-Probability
  environment:
    HOME: /media/data/conrad/.local/share/lxc/base/rootfs/home/ubuntu
  tags:
    - afp-sessions

- name: Build AFP sessions
  command: >
           {{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/Isabelle2022/bin/isabelle build
           -d {{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/afp/thys -bv
           -o timeout_scale=5
           {{ item }}
  with_items:
    - Automatic_Refinement
    - Refine_Monadic
    - Collections
    - Sepref_Prereq
    - Refine_Imperative_HOL
  environment:
    HOME: /media/data/conrad/.local/share/lxc/base/rootfs/home/ubuntu
  tags:
    - afp-sessions

- name: Set correct file rights of .isabelle in home dir of unprivileged user in container
  file:
    path: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/home/ubuntu/.isabelle"
    owner: "10001001"
    group: "10001001"
    recurse: yes
    state: directory
    mode: 0755

- name: Edit LXC base container config for network access
  blockinfile:
    name: "{{ config.afp.container_home }}/.local/share/lxc/base/config"
    block: |
      lxc.net.0.type = veth
      lxc.net.0.link = lxcbr0
      lxc.net.0.flags = up
      lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx

- name: Install packages in LXC container
  shell: "{{ item }}"
  with_items:
    - lxc-start -n base
    - lxc-wait -n base -s RUNNING
    - lxc-attach -n base -- apt-get -y update
    - lxc-attach -n base -- apt-get -y install lib32stdc++6 unzip texlive-full fontconfig
    - lxc-stop -n base
  become: true
  become_user: conrad
  become_method: sudo

- name: Remove network config from LXC base container config
  blockinfile:
    name: "{{ config.afp.container_home }}/.local/share/lxc/base/config"
