---

- name: Prepare LXC configuration directory
  file: path={{ config.afp.container_home }}/.config/lxc state=directory owner=root group=root mode=0755

- name: Copy LXC configuration
  template: src=default.conf dest={{ config.afp.container_home }}/.config/lxc/default.conf owner=root group=root mode=0644

- name: Edit /etc/lxc/lxc-usernet
  lineinfile: name=/etc/lxc/lxc-usernet line='conrad veth lxcbr0 2'

- name: Restart lxc-net.service
  service: name=lxc-net.service state=restarted

- name: List LXC containers
  shell: lxc-ls -1
  register: afp_lxc
  become: yes
  become_user: conrad
  become_method: sudo

- name: Create LXC base container
  shell: lxc-create -n base -t download --bdev dir -- -d ubuntu -r focal -a amd64
  when: "afp_lxc.stdout.find('base') == -1"
  become: yes
  become_user: conrad
  become_method: sudo

- name: Copy resolv.conf
  copy: src=/etc/resolv.conf dest={{ config.afp.container_home }}/.local/share/lxc/base/rootfs/etc/resolv.conf remote_src=true owner=root group=root mode=0644

- name: Download Isabelle
  get_url: url=https://isabelle.in.tum.de/website-Isabelle{{ config.isabelle.version }}/dist/Isabelle{{ config.isabelle.version }}_linux.tar.gz dest=/media/data/isabelle{{ config.isabelle.version }}.tar.gz

- name: Unpack Isabelle into LXC base container
  unarchive: src=/media/data/isabelle{{ config.isabelle.version }}.tar.gz copy=false creates=Isabelle{{ config.isabelle.version }} dest={{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt owner=root group=root

- name: Clone AFP
  hg: dest={{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/afp repo=https://foss.heptapod.net/isa-afp/afp-{{ config.afp.version }} revision=default force=yes purge=yes

- name: Clone Linter
  git: dest={{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/linter repo=https://github.com/isabelle-prover/isabelle-linter version={{ config.linter.version }} force=yes

- name: Fix AFP default origin
  lineinfile: name={{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/afp/.hg/hgrc regexp=^default line='default = https://foss.heptapod.net/isa-afp/afp-{{ config.afp.version }}'

- name: Change ownership of AFP
  file:
    path: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/afp"
    state: directory
    recurse: yes
    owner: conrad
    group: conrad

- name: Add APF symlink
  file:
    src: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/afp"
    dest: "/opt/afp"
    state: link

- name: Add Linter symlink
  file:
    src: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/linter"
    dest: "/opt/linter"
    state: link

- name: Create .isabelle/Isabelle{{ config.isabelle.version }}/etc/ in home dir of unprivileged user in container
  file:
    path: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/home/ubuntu/.isabelle/Isabelle{{ config.isabelle.version }}/etc"
    owner: "10001001"
    group: "10001001"
    state: directory
    mode: 0755

- name: Configure Isabelle
  blockinfile:
    name: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/home/ubuntu/.isabelle/Isabelle{{ config.isabelle.version }}/etc/settings"
    create: yes
    block: |
      ISABELLE_TOOL_JAVA_OPTIONS="-Xmx2G"
      ML_OPTIONS="-H 4000 --maxheap 4G"
      ML_HOME="$POLYML_HOME/$ML_PLATFORM"

- name: Add AFP component
  blockinfile:
    name: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/home/ubuntu/.isabelle/Isabelle{{ config.isabelle.version }}/etc/components"
    create: yes
    block: |
      /opt/afp
      /opt/linter

- name: Download additional AFP components
  command: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/Isabelle{{ config.isabelle.version }}/bin/isabelle components -a"
  environment:
    HOME: /media/data/conrad/.local/share/lxc/base/rootfs/home/ubuntu

- name: Build Isabelle sessions
  command: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/Isabelle{{ config.isabelle.version }}/bin/isabelle build -o threads=2 -bv {{ item }}"
  with_items:
    - Pure
    - HOL
    - HOL-Library
    - HOL-Analysis
    - HOL-Probability
  environment:
    HOME: /media/data/conrad/.local/share/lxc/base/rootfs/home/ubuntu
  tags:
    - afp-sessions

- name: Build AFP sessions
  command: >
           {{ config.afp.container_home }}/.local/share/lxc/base/rootfs/opt/Isabelle{{ config.isabelle.version }}/bin/isabelle build
           -d '$AFP' -bv
           -o timeout_scale=5
           {{ item }}
  with_items:
    - Automatic_Refinement
    - Refine_Monadic
    - Collections
    - Sepref_Prereq
    - Refine_Imperative_HOL
  environment:
    HOME: /media/data/conrad/.local/share/lxc/base/rootfs/home/ubuntu
  tags:
    - afp-sessions

- name: Set correct file rights of .isabelle in home dir of unprivileged user in container
  file:
    path: "{{ config.afp.container_home }}/.local/share/lxc/base/rootfs/home/ubuntu/.isabelle"
    owner: "10001001"
    group: "10001001"
    recurse: yes
    state: directory
    mode: 0755

- name: Edit LXC base container config for network access
  blockinfile:
    name: "{{ config.afp.container_home }}/.local/share/lxc/base/config"
    block: |
      lxc.net.0.type = veth
      lxc.net.0.link = lxcbr0
      lxc.net.0.flags = up
      lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx

- name: Install packages in LXC container
  shell: "{{ item }}"
  with_items:
    - lxc-start -n base
    - lxc-wait -n base -s RUNNING
    - lxc-attach -n base -- locale-gen en_US.UTF-8
    - lxc-attach -n base -- locale-gen en_DK.UTF-8
    - lxc-attach -n base -- locale-gen de_DE.UTF-8
    - lxc-attach -n base -- apt-get -y update
    - lxc-attach -n base -- apt-get -y install lib32stdc++6 unzip texlive-full fontconfig
    - lxc-stop -n base
  become: true
  become_user: conrad
  become_method: sudo

- name: Remove network config from LXC base container config
  blockinfile:
    name: "{{ config.afp.container_home }}/.local/share/lxc/base/config"
