---
ansible_python_interpreter: python3

config:
  worker:
    jenkins_home: "/media/data/jenkins"

  mail:
    host: postout.lrz.de
    port: 465
    user: ge73ruk
    sender: ge73ruk@mytum.de

  github:
    user: isabelle-bot

  isabelle:
    version: 2023

  afp:
    version: 2023
    container_home: "/media/data/conrad"
    git: "https://github.com/isabelle-prover/afp-submission.git"
    sub_id_min: 10000001
    sub_id_max: 10100000
    sub_id_count: 100000

    site_home: "/srv/afp"

  linter:
    version: Isabelle2023-v1.0.0

  apache:
    cert_name: isabelle-tls-certs

    webroots:
      - /var/www/ci
      - /srv/afp
      - /var/www/afp-devel

    configs:
      - ci.conf
      - ci-ssl.conf
      - isa-afp.conf
      - isa-afp-ssl.conf

  jenkins:
    scripts:
      - users.groovy
      - security.groovy
      - credentials.groovy
      - executors.groovy
      - mail.groovy
      - hg.groovy

    jobs:
      - isabelle-all
      - isabelle-nightly-benchmark
      - isabelle-nightly-slow
      - testboard
      - afp_testboard
      - isabelle-notify
      - isabelle-distributed

    views:
      - default
      - nightly
      - testboard
