---
ansible_python_interpreter: python3
ansible_remote_tmp: /tmp

config:
  ssl_domains:
    ci: ci.isabelle.systems
    afp: www.isa-afp.org
    afp_devel: devel.isa-afp.org
    afp_short: isa-afp.org

  domains:
    afp_submit: afp-submit.proof.cit.tum.de
    build: build.proof.cit.tum.de
    search: search.isabelle.in.tum.de

  mail:
    host: mail.cit.tum.de
    port: 465

  build:
    home: /home/build
    data: /srv/build
    mail:
      sender: ci@proof.cit.tum.de
      admin: isabelle-ci@mailman46.in.tum.de

  github:
    user: isabelle-bot

  isabelle:
    version: 2024

  afp:
    version: 2024
    container_home: "/media/data/conrad"
    git: "https://github.com/isabelle-prover/afp-submission.git"
    sub_id_min: 10000001
    sub_id_max: 10100000
    sub_id_count: 100000

    site_home: "/srv/afp"

    mail:
      sender: afp@proof.cit.tum.de
      admin: afp@proof.cit.tum.de
      editors: afp-submit@in.tum.de

  linter:
    version: Isabelle2024-v1.0.1

  apache:
    cert_name: isabelle-tls-certs

    webroots:
      - /var/www/ci
      - /srv/afp
      - /var/www/afp-devel

    configs:
      - ci.conf
      - ci-ssl.conf
      - isa-afp.conf
      - isa-afp-ssl.conf
