---

- name: Install packages with Homebrew
  homebrew:
    state: present
    name:
      - mercurial
      - mlton
      - swi-prolog
      - smlnj
      - haskell-stack

- name: Install packages with Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - mactex
    - java

- name: Create Jenkins user
  user: name=jenkins uid=902 shell=/bin/sh home={{ config.worker.jenkins_home }}
  become: yes
  become_method: sudo

- name: Prepare .ssh directory
  file: path={{ config.worker.jenkins_home }}/.ssh state=directory owner=jenkins group=wheel mode=0700
  become: yes
  become_method: sudo

- name: Copy authorized_keys file
  copy: src=authorized_keys dest={{ config.worker.jenkins_home }}/.ssh/authorized_keys owner=jenkins group=wheel mode=0644
  become: yes
  become_method: sudo

# from <https://gist.github.com/mwf/20cbb260ad2490d7faaa> and <https://superuser.com/a/166219>
- name: Enable SSH for Jenkins user
  shell: "{{ item }}"
  with_items:
    - dscl . append /Groups/com.apple.access_ssh GroupMembership jenkins
    - dscl . append /Groups/com.apple.access_ssh groupmembers $(dscl . read /Users/jenkins GeneratedUID | cut -d " " -f 2)
  become: yes
  become_method: sudo

- name: Copy Java wrapper script
  copy: src=java dest={{ config.worker.jenkins_home}}/java owner=jenkins group=wheel mode=0755
  become: yes
  become_method: sudo
