---

- name: Install packages
  apt:
    state: present
    update_cache: yes
    name:
      - openjdk-17-jre
      - m4
      - mercurial
      - curl
      - libgomp1
      - libgmp-dev
      - unzip
      - swi-prolog
      - smlnj
      - lib32stdc++6
      - texlive-full
