---

- name: Install packages
  apt:
    state: present
    update_cache: yes
    name:
      - nfs-common

- name: Create mount point dirs
  file: path=/media/isabelle-cluster state=directory owner=slurm group=slurm mode=0755

- name: Create Isabelle home mount point
  file: path=/media/isabelle-cluster/isabelle state=directory

- name: Create Isabelle user home mount point
  file: path=/media/isabelle-cluster/.isabelle state=directory

- name: Create Isabelle heaps mount point
  file: path=/media/isabelle-cluster/heaps state=directory

- name: Create Isabelle browser info mount
  file: path=/media/isabelle-cluster/browser_info state=directory

- name: Register NFS mounts
  blockinfile:
    name: /etc/fstab
    block: |
      {{ groups['slurm_master'][0] }}:{{ config.worker.jenkins_home }}/workspace/isabelle-distributed /media/isabelle-cluster/isabelle nfs ro 0 0
      {{ groups['slurm_master'][0] }}:{{ config.worker.jenkins_home }}/.isabelle /media/isabelle-cluster/.isabelle nfs ro 0 0
      {{ groups['slurm_master'][0] }}:{{ config.worker.jenkins_home }}/workspace/heaps /media/isabelle-cluster/heaps nfs rw 0 0
      {{ groups['slurm_master'][0] }}:{{ config.worker.jenkins_home }}/workspace/heaps /media/isabelle-cluster/browser_info nfs rw 0 0

- name: Mount NFS
  shell: mount -a