---

- name: Install packages
  apt:
    state: present
    update_cache: yes
    name:
      - munge
      - slurmd

- name: Create munge user
  user: name=munge create_home=false group=munge system=yes shell=/sbin/nologin

- name: Create munge group
  group: name=munge system=yes

- name: Create slurm user
  user: name=slurm uid=905 shell=/bin/sh group=slurm

- name: Create slurm group
  group: name=slurm gid=905

- name: Copy munge key
  copy: src=munge.key dest=/etc/munge/munge.key owner=munge group=munge mode=0400

- name: Start and enable munge service
  service: name=munge enabled=true state=restarted

- name: Add FQN to hosts
  lineinfile: name=/etc/hosts regexp='127.0.1.1\s.*' line='127.0.1.1 {{ inventory_hostname }} {{ ansible_hostname }}'

- name: Write slurm conf
  template: src=slurm.conf dest=/etc/slurm/slurm.conf owner=slurm group=slurm mode=0650

- name: Copy slurm cgroup conf
  copy: src=cgroup.conf dest=/etc/slurm/cgroup.conf owner=slurm group=slurm mode=0650

- name: Add slurm nodes
  lineinfile:
    name: /etc/slurm/slurm.conf
    line: NodeName={{ item }} SocketsPerBoard={{ hostvars[item]['sockets'] }} CoresPerSocket={{ hostvars[item]['cores'] }} ThreadsPerCore={{ hostvars[item]['threads'] }} RealMemory={{ hostvars[item]['slurm_memkb'] }} State=UNKNOWN
  loop: "{{ groups['slurm_worker'] }}"

- name: Start and enable slurm service
  service: name=slurmd enabled=true state=restarted