---

- name: Configure AFP submission checker
  hosts: afp
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: afp, tags: [ 'afp' ] }

- name: Configure and deploy Apache
  hosts: leader
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: apache, tags: [ 'apache' ] }

- name: Configure and deploy build manager
  hosts: build_manager
  become: yes
  become_method: sudo

  vars:
    ansible_remote_tmp: /tmp/ansible

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: build-manager, tags: [ 'build-manager' ] }

- name: Configure cluster nodes
  hosts: cluster_node
  become: yes
  become_method: sudo

  vars:
    ansible_remote_tmp: /tmp/ansible

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: cluster-node, tags: [ 'cluster-node' ] }