---

- name: Configure LRZ workers
  hosts: worker_lrz
  become: yes
  become_method: sudo

  roles:
    - { role: lrz-base, tags: [ 'lrz-base' ] }
    - { role: worker-lrz, tags: [ 'worker', 'worker-lrz' ] }

- name: Configure MTA workers
  hosts: worker_mta
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: worker-mta, tags: [ 'worker', 'worker-mta' ] }

- name: Configure cluster workers
  hosts: worker_cluster
  become: yes
  become_method: sudo

  vars:
    ansible_remote_tmp: /tmp/ansible

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: worker-cluster, tags: [ 'worker', 'worker-cluster' ] }

- name: Configure AFP submission checker
  hosts: afp
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: afp, tags: [ 'afp' ] }

- name: Configure and deploy Apache and Jenkins
  hosts: leader
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: apache, tags: [ 'apache' ] }
    - { role: jenkins, tags: [ 'jenkins' ] }

- name: Configure cluster nodes
  hosts: cluster_node
  become: yes
  become_method: sudo

  vars:
    ansible_remote_tmp: /tmp/ansible

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: cluster-node, tags: [ 'cluster-node' ] }