---

- name: Configure LRZ workers
  hosts: worker_lrz
  become: yes
  become_method: sudo

  roles:
    - { role: lrz-base, tags: [ 'lrz-base' ] }
    - { role: worker-lrz, tags: [ 'worker', 'worker-lrz' ] }

- name: Configure MTA workers
  hosts: worker_mta
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: worker-mta, tags: [ 'worker', 'worker-mta' ] }

- name: Configure AFP submission checker
  hosts: afp
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: lrz-base, tags: [ 'lrz-base' ] }
    - { role: afp, tags: [ 'afp' ] }

- name: Configure and deploy Apache and Jenkins
  hosts: leader
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: apache, tags: [ 'apache' ] }
    - { role: jenkins, tags: [ 'jenkins' ] }

- name: Configure slurm master
  hosts: slurm_master
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: slurm-master, tags: [ 'slurm-master' ] }
    - { role: slurm, tag: ['slurm'] }

- name: Configure slurm workers
  hosts: slurm_worker
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: slurm, tags: [ 'slurm', 'slurm-worker' ] }