---

- name: Configure AFP submission checker
  hosts: afp

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: afp, tags: [ 'afp' ] }

- name: Configure and deploy Apache
  hosts: leader

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: apache, tags: [ 'apache' ] }

- name: Configure and deploy build manager
  hosts: build_manager

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: build-manager, tags: [ 'build-manager' ] }

- name: Configure cluster nodes
  hosts: cluster_node

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: cluster-node, tags: [ 'cluster-node' ] }