---

- name: Configure LRZ workers
  hosts: worker-lrz
  become: yes
  become_method: sudo

  roles:
    - { role: lrz-base, tags: [ 'lrz-base' ] }
    - { role: worker-lrz, tags: [ 'worker', 'worker-lrz' ] }

- name: Configure LRZ-large workers
  hosts: worker-lrz-large
  become: yes
  become_method: sudo

  roles:
    - { role: lrz-base, tags: [ 'lrz-base' ] }
    - { role: worker-lrz, tags: [ 'worker', 'worker-lrz' ] }
    - { role: worker-lrz-large, tags: [ 'worker-lrz-large' ] }

- name: Configure MTA workers
  hosts: worker-mta
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: worker-mta, tags: [ 'worker', 'worker-mta' ] }

- name: Configure AFP submission checker
  hosts: afp
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: lrz-base, tags: [ 'lrz-base' ] }
    - { role: afp, tags: [ 'afp' ] }

- name: Configure and deploy Apache and Jenkins
  hosts: leader
  become: yes
  become_method: sudo

  vars_files:
    - vars/secrets.yml

  roles:
    - { role: apache, tags: [ 'apache' ] }
    - { role: jenkins, tags: [ 'jenkins' ] }
