---

- name: Install packages
  apt:
    state: present
    update_cache: yes
    name:
      - curl
      - m4
      - libgomp1
      - libgmp-dev
      - unzip
      - swi-prolog
      - smlnj
      - lib32stdc++6
      - texlive-full
      - libzarith-ocaml
      - python3-pip
      - python3-dev
      - libpq-dev
      - postgresql-14
      - caddy

- name: Enable psycopg2 for ansible
  become: true
  pip:
    name: psycopg2
    state: present

- name: Create build user
  user: name=build shell=/bin/bash home={{ config.build.home }} group=isabelle system=yes

- name: Prepare .ssh directory
  file: path={{ config.build.home }}/.ssh state=directory owner=build group=root mode=0700

- name: Copy authorized_keys file
  copy: src=authorized_keys dest={{ config.build.home }}/.ssh/authorized_keys owner=build group=root mode=0600

- name: Copy SSH config
  copy: src=ssh_config dest={{ config.build.home }}/.ssh/config owner=build group=root mode=0644

- name: Copy private SSH key for worker access
  copy: content="{{ config.cluster.ssh_key }}" dest={{ config.build.home }}/.ssh/id_cluster owner=build group=root mode=0600