---

- name: Ensure ansible group exists
  group: name=ansible state=present

- name: Download caddy key
  get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /etc/apt/trusted.gpg.d/caddy.asc

- name: Add repo
  apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/caddy.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present

- name: Install packages
  apt:
    state: present
    update_cache: yes
    name:
      - openjdk-17-jre
      - curl
      - m4
      - libgomp1
      - libgmp-dev
      - unzip
      - swi-prolog
      - smlnj
      - lib32stdc++6
      - texlive-full
      - libzarith-ocaml
      - python3-pip
      - python3-dev
      - libpq-dev
      - postgresql-14
      - caddy

- name: Enable psycopg2 for ansible
  become: true
  pip:
    name: psycopg2
    state: present

- name: Create build user
  user: name=build shell=/bin/bash home={{ config.build.home }} group=isabelle system=yes

- name: Prepare .ssh directory
  file: path={{ config.build.home }}/.ssh state=directory owner=build group=root mode=0700

- name: Copy SSH config
  copy: src=ssh_config dest={{ config.build.home }}/.ssh/config owner=build group=root mode=0644

- name: Copy public SSH key
  copy: src=id_build.pub dest={{ config.build.home }}/.ssh/id_build.pub owner=build group=root mode=0644

- name: Copy private SSH key
  copy: content="{{ config.build.ssh_key }}" dest={{ config.build.home }}/.ssh/id_build owner=build group=root mode=0600

- name: Copy public SSH key for worker access
  copy: src=id_cluster.pub dest={{ config.build.home }}/.ssh/id_cluster.pub owner=build group=root mode=0644

- name: Copy private SSH key for worker access
  copy: content="{{ config.cluster.ssh_key }}" dest={{ config.build.home }}/.ssh/id_cluster owner=build group=root mode=0600