---

- name: Prepare mount point
  file: path=/media/data/ state=directory owner=root group=root mode=0755

- name: Create ext4 filesystem on /dev/vdb
  filesystem: fstype=ext4 dev=/dev/vdb

- name: Fix fstab
  lineinfile: dest=/etc/fstab regexp=^/dev/vdb line='/dev/vdb /media/data ext4 defaults 0 0'

- name: Mount hard disk
  mount: name=/media/data src=/dev/vdb fstype=ext4 state=mounted

- name: Disable root password
  shell: passwd -l root

- name: Prepare .ssh directory
  file: path=/root/.ssh state=directory owner=root group=root mode=0700

- name: Copy authorized_keys file
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys owner=root group=root mode=0644
